[tool.poetry]
name = "square-area"
version = "0.1.0"
description = ""
authors = ["serena iadevaia <iadevaia95@outlook.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
